services:
  db:
    image: postgres:17.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
