name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      APP_PORT: "3000"
      LOG_LEVEL: debug
      BODY_LIMIT_BYTES: "1048576"
      DATABASE_URL: "postgresql://username:password@localhost:5432/test_db"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Start docker containers
        run: |
          docker compose up -d
          # Wait for services to be ready (maybe add health checks)
          sleep 5

      - name: Setup database
        run: npm run db:migrate

      - name: Test
        run: npm run test

      - name: Stop docker containers
        run: docker compose down
